import type { VerseInfo } from '../../types';

export const CHRISTIAN_LIVING: VerseInfo[] = [
  // Previous verses remain...
  // Adding 45 new verses
  { reference: 'MAT.5.16', category: 'Christian Living' },
  { reference: 'MAT.6.33', category: 'Christian Living' },
  { reference: 'MAT.7.12', category: 'Christian Living' },
  { reference: 'MAT.22.37', category: 'Christian Living' },
  { reference: 'MAT.28.19', category: 'Christian Living' },
  { reference: 'MRK.12.30', category: 'Christian Living' },
  { reference: 'LUK.9.23', category: 'Christian Living' },
  { reference: 'JHN.13.35', category: 'Christian Living' },
  { reference: 'JHN.15.4', category: 'Christian Living' },
  { reference: 'JHN.15.8', category: 'Christian Living' },
  { reference: 'ACT.1.8', category: 'Christian Living' },
  { reference: 'ROM.6.11', category: 'Christian Living' },
  { reference: 'ROM.6.13', category: 'Christian Living' },
  { reference: 'ROM.8.5', category: 'Christian Living' },
  { reference: 'ROM.12.1', category: 'Christian Living' },
  { reference: 'ROM.13.13', category: 'Christian Living' },
  { reference: 'ROM.14.8', category: 'Christian Living' },
  { reference: '1CO.6.19', category: 'Christian Living' },
  { reference: '1CO.10.31', category: 'Christian Living' },
  { reference: '2CO.5.7', category: 'Christian Living' },
  { reference: '2CO.5.15', category: 'Christian Living' },
  { reference: '2CO.7.1', category: 'Christian Living' },
  { reference: 'GAL.2.20', category: 'Christian Living' },
  { reference: 'GAL.5.16', category: 'Christian Living' },
  { reference: 'GAL.5.22', category: 'Christian Living' },
  { reference: 'EPH.4.1', category: 'Christian Living' },
  { reference: 'EPH.4.22', category: 'Christian Living' },
  { reference: 'EPH.5.1', category: 'Christian Living' },
  { reference: 'EPH.5.8', category: 'Christian Living' },
  { reference: 'PHP.1.27', category: 'Christian Living' },
  { reference: 'PHP.2.5', category: 'Christian Living' },
  { reference: 'PHP.4.8', category: 'Christian Living' },
  { reference: 'COL.3.1', category: 'Christian Living' },
  { reference: 'COL.3.17', category: 'Christian Living' },
  { reference: '1TH.4.1', category: 'Christian Living' },
  { reference: '1TH.5.16', category: 'Christian Living' },
  { reference: '2TI.2.15', category: 'Christian Living' },
  { reference: 'TIT.2.12', category: 'Christian Living' },
  { reference: 'HEB.12.1', category: 'Christian Living' },
  { reference: 'HEB.13.16', category: 'Christian Living' },
  { reference: 'JAM.1.22', category: 'Christian Living' },
  { reference: '1PE.1.15', category: 'Christian Living' },
  { reference: '1PE.2.11', category: 'Christian Living' },
  { reference: '1JN.1.7', category: 'Christian Living' },
  { reference: '1JN.2.6', category: 'Christian Living' }
];
