import type { VerseInfo } from '../../types';

export const COMFORT: VerseInfo[] = [
  // Existing verses...
  { reference: 'PSA.23.4', category: 'Comfort & Peace' },
  { reference: 'MAT.11.28', category: 'Comfort & Peace' },
  { reference: 'JHN.14.27', category: 'Comfort & Peace' },
  { reference: 'PHP.4.7', category: 'Comfort & Peace' },
  { reference: '2CO.1.3', category: 'Comfort & Peace' },
  { reference: 'PSA.34.18', category: 'Comfort & Peace' },
  { reference: 'ISA.26.3', category: 'Comfort & Peace' },
  { reference: 'PSA.55.22', category: 'Comfort & Peace' },
  { reference: 'MAT.5.4', category: 'Comfort & Peace' },
  { reference: 'ROM.15.13', category: 'Comfort & Peace' },
  { reference: 'PSA.119.50', category: 'Comfort & Peace' },
  { reference: 'JHN.16.33', category: 'Comfort & Peace' },
  { reference: '2TH.2.16', category: 'Comfort & Peace' },
  { reference: 'REV.21.4', category: 'Comfort & Peace' },
  { reference: 'PSA.94.19', category: 'Comfort & Peace' },
  { reference: 'ISA.49.13', category: 'Comfort & Peace' },
  { reference: 'PSA.147.3', category: 'Comfort & Peace' },
  { reference: 'MAT.6.25', category: 'Comfort & Peace' },
  { reference: 'PHP.4.6', category: 'Comfort & Peace' },
  { reference: 'PSA.46.1', category: 'Comfort & Peace' },
  // Adding new verses
  { reference: 'ISA.41.10', category: 'Comfort & Peace' },
  { reference: 'PSA.27.1', category: 'Comfort & Peace' },
  { reference: '2CO.1.4', category: 'Comfort & Peace' },
  { reference: 'ISA.43.2', category: 'Comfort & Peace' },
  { reference: 'PSA.91.1', category: 'Comfort & Peace' },
  { reference: 'ROM.8.28', category: 'Comfort & Peace' },
  { reference: 'DEU.31.8', category: 'Comfort & Peace' },
  { reference: 'PSA.34.17', category: 'Comfort & Peace' },
  { reference: 'ISA.40.31', category: 'Comfort & Peace' },
  { reference: 'PSA.32.7', category: 'Comfort & Peace' },
  { reference: 'MAT.11.29', category: 'Comfort & Peace' },
  { reference: 'PSA.73.26', category: 'Comfort & Peace' },
  { reference: 'ISA.51.12', category: 'Comfort & Peace' },
  { reference: 'PSA.145.18', category: 'Comfort & Peace' },
  { reference: '2CO.7.6', category: 'Comfort & Peace' },
  { reference: 'PSA.119.76', category: 'Comfort & Peace' },
  { reference: 'ISA.66.13', category: 'Comfort & Peace' },
  { reference: 'PSA.23.1', category: 'Comfort & Peace' },
  { reference: 'JER.29.11', category: 'Comfort & Peace' },
  { reference: 'PSA.119.52', category: 'Comfort & Peace' },
  { reference: 'LAM.3.22', category: 'Comfort & Peace' },
  { reference: 'PSA.16.9', category: 'Comfort & Peace' },
  { reference: 'ISA.30.15', category: 'Comfort & Peace' },
  { reference: 'PSA.62.1', category: 'Comfort & Peace' },
  { reference: 'MAT.5.9', category: 'Comfort & Peace' }
];
