import type { VerseInfo } from '../../types';

export const FAITH_TRUST: VerseInfo[] = [
  // Previous verses remain...
  // Adding 40 new verses
  { reference: 'MAT.21.22', category: 'Faith & Trust' },
  { reference: 'JHN.14.1', category: 'Faith & Trust' },
  { reference: 'ROM.5.1', category: 'Faith & Trust' },
  { reference: 'GAL.2.20', category: 'Faith & Trust' },
  { reference: 'EPH.3.17', category: 'Faith & Trust' },
  { reference: 'HEB.10.22', category: 'Faith & Trust' },
  { reference: 'HEB.11.7', category: 'Faith & Trust' },
  { reference: 'HEB.11.11', category: 'Faith & Trust' },
  { reference: 'JAM.1.3', category: 'Faith & Trust' },
  { reference: '1PE.1.8', category: 'Faith & Trust' },
  { reference: 'ROM.4.3', category: 'Faith & Trust' },
  { reference: 'ROM.4.5', category: 'Faith & Trust' },
  { reference: 'ROM.4.9', category: 'Faith & Trust' },
  { reference: 'ROM.4.16', category: 'Faith & Trust' },
  { reference: 'ROM.4.19', category: 'Faith & Trust' },
  { reference: 'ROM.4.21', category: 'Faith & Trust' },
  { reference: 'ROM.10.10', category: 'Faith & Trust' },
  { reference: 'ROM.10.11', category: 'Faith & Trust' },
  { reference: 'ROM.10.17', category: 'Faith & Trust' },
  { reference: 'ROM.14.23', category: 'Faith & Trust' },
  { reference: '1CO.2.5', category: 'Faith & Trust' },
  { reference: '1CO.16.13', category: 'Faith & Trust' },
  { reference: '2CO.1.24', category: 'Faith & Trust' },
  { reference: '2CO.4.13', category: 'Faith & Trust' },
  { reference: '2CO.5.7', category: 'Faith & Trust' },
  { reference: 'GAL.3.2', category: 'Faith & Trust' },
  { reference: 'GAL.3.7', category: 'Faith & Trust' },
  { reference: 'GAL.3.9', category: 'Faith & Trust' },
  { reference: 'GAL.3.14', category: 'Faith & Trust' },
  { reference: 'GAL.3.22', category: 'Faith & Trust' },
  { reference: 'EPH.2.8', category: 'Faith & Trust' },
  { reference: 'EPH.3.12', category: 'Faith & Trust' },
  { reference: 'EPH.3.17', category: 'Faith & Trust' },
  { reference: 'EPH.6.16', category: 'Faith & Trust' },
  { reference: 'COL.1.23', category: 'Faith & Trust' },
  { reference: 'COL.2.7', category: 'Faith & Trust' },
  { reference: '1TH.1.3', category: 'Faith & Trust' },
  { reference: '1TH.3.10', category: 'Faith & Trust' },
  { reference: '2TH.1.3', category: 'Faith & Trust' },
  { reference: '2TH.1.11', category: 'Faith & Trust' }
];
