import type { VerseInfo } from '../../types';

export const GODS_ATTRIBUTES: VerseInfo[] = [
  // Previous verses remain...
  // Adding 40 new verses
  { reference: 'GEN.1.1', category: "God's Attributes" },
  { reference: 'EXO.3.14', category: "God's Attributes" },
  { reference: 'EXO.15.11', category: "God's Attributes" },
  { reference: 'EXO.34.6', category: "God's Attributes" },
  { reference: 'NUM.23.19', category: "God's Attributes" },
  { reference: 'DEU.4.24', category: "God's Attributes" },
  { reference: 'DEU.7.9', category: "God's Attributes" },
  { reference: 'DEU.32.4', category: "God's Attributes" },
  { reference: '1SA.2.2', category: "God's Attributes" },
  { reference: '2SA.22.31', category: "God's Attributes" },
  { reference: '1CH.29.11', category: "God's Attributes" },
  { reference: 'NEH.9.17', category: "God's Attributes" },
  { reference: 'JOB.36.26', category: "God's Attributes" },
  { reference: 'JOB.37.23', category: "God's Attributes" },
  { reference: 'PSA.7.11', category: "God's Attributes" },
  { reference: 'PSA.19.1', category: "God's Attributes" },
  { reference: 'PSA.47.2', category: "God's Attributes" },
  { reference: 'PSA.90.2', category: "God's Attributes" },
  { reference: 'PSA.93.1', category: "God's Attributes" },
  { reference: 'PSA.99.9', category: "God's Attributes" },
  { reference: 'PSA.103.8', category: "God's Attributes" },
  { reference: 'PSA.115.3', category: "God's Attributes" },
  { reference: 'PSA.135.5', category: "God's Attributes" },
  { reference: 'PSA.145.3', category: "God's Attributes" },
  { reference: 'PSA.147.5', category: "God's Attributes" },
  { reference: 'ISA.6.3', category: "God's Attributes" },
  { reference: 'ISA.40.28', category: "God's Attributes" },
  { reference: 'ISA.44.6', category: "God's Attributes" },
  { reference: 'ISA.55.9', category: "God's Attributes" },
  { reference: 'ISA.57.15', category: "God's Attributes" },
  { reference: 'JER.10.10', category: "God's Attributes" },
  { reference: 'JER.23.24', category: "God's Attributes" },
  { reference: 'JER.32.17', category: "God's Attributes" },
  { reference: 'DAN.4.35', category: "God's Attributes" },
  { reference: 'MAL.3.6', category: "God's Attributes" },
  { reference: 'JHN.4.24', category: "God's Attributes" },
  { reference: 'ROM.11.33', category: "God's Attributes" },
  { reference: '1TI.1.17', category: "God's Attributes" },
  { reference: 'HEB.4.13', category: "God's Attributes" },
  { reference: 'REV.4.8', category: "God's Attributes" }
];
