import type { VerseInfo } from '../../types';

export const GOSPEL_SALVATION: VerseInfo[] = [
  // Previous verses remain...
  // Adding 40 new verses
  { reference: 'MAT.1.21', category: 'Gospel & Salvation' },
  { reference: 'MAT.4.17', category: 'Gospel & Salvation' },
  { reference: 'MAT.11.28', category: 'Gospel & Salvation' },
  { reference: 'MAT.28.19', category: 'Gospel & Salvation' },
  { reference: 'MRK.1.15', category: 'Gospel & Salvation' },
  { reference: 'MRK.16.16', category: 'Gospel & Salvation' },
  { reference: 'LUK.19.10', category: 'Gospel & Salvation' },
  { reference: 'JHN.1.12', category: 'Gospel & Salvation' },
  { reference: 'JHN.3.3', category: 'Gospel & Salvation' },
  { reference: 'JHN.3.36', category: 'Gospel & Salvation' },
  { reference: 'JHN.5.24', category: 'Gospel & Salvation' },
  { reference: 'JHN.6.37', category: 'Gospel & Salvation' },
  { reference: 'JHN.6.47', category: 'Gospel & Salvation' },
  { reference: 'JHN.10.9', category: 'Gospel & Salvation' },
  { reference: 'JHN.11.25', category: 'Gospel & Salvation' },
  { reference: 'ACT.2.21', category: 'Gospel & Salvation' },
  { reference: 'ACT.3.19', category: 'Gospel & Salvation' },
  { reference: 'ACT.4.12', category: 'Gospel & Salvation' },
  { reference: 'ACT.16.31', category: 'Gospel & Salvation' },
  { reference: 'ROM.1.16', category: 'Gospel & Salvation' },
  { reference: 'ROM.3.23', category: 'Gospel & Salvation' },
  { reference: 'ROM.5.8', category: 'Gospel & Salvation' },
  { reference: 'ROM.5.9', category: 'Gospel & Salvation' },
  { reference: 'ROM.6.23', category: 'Gospel & Salvation' },
  { reference: 'ROM.8.1', category: 'Gospel & Salvation' },
  { reference: 'ROM.10.9', category: 'Gospel & Salvation' },
  { reference: 'ROM.10.13', category: 'Gospel & Salvation' },
  { reference: '2CO.5.17', category: 'Gospel & Salvation' },
  { reference: '2CO.5.21', category: 'Gospel & Salvation' },
  { reference: 'GAL.2.16', category: 'Gospel & Salvation' },
  { reference: 'GAL.3.26', category: 'Gospel & Salvation' },
  { reference: 'EPH.1.7', category: 'Gospel & Salvation' },
  { reference: 'EPH.2.8', category: 'Gospel & Salvation' },
  { reference: 'PHP.2.12', category: 'Gospel & Salvation' },
  { reference: 'COL.1.13', category: 'Gospel & Salvation' },
  { reference: '1TH.5.9', category: 'Gospel & Salvation' },
  { reference: '2TI.1.9', category: 'Gospel & Salvation' },
  { reference: 'TIT.3.5', category: 'Gospel & Salvation' },
  { reference: 'HEB.7.25', category: 'Gospel & Salvation' },
  { reference: '1PE.1.3', category: 'Gospel & Salvation' }
];
