import type { VerseInfo } from '../../types';

export const GUIDANCE: VerseInfo[] = [
  // Previous verses remain...
  // Adding 40 new verses
  { reference: 'GEN.24.27', category: 'Divine Guidance' },
  { reference: 'EXO.15.13', category: 'Divine Guidance' },
  { reference: 'DEU.1.33', category: 'Divine Guidance' },
  { reference: 'PSA.5.8', category: 'Divine Guidance' },
  { reference: 'PSA.23.2', category: 'Divine Guidance' },
  { reference: 'PSA.25.5', category: 'Divine Guidance' },
  { reference: 'PSA.27.11', category: 'Divine Guidance' },
  { reference: 'PSA.31.3', category: 'Divine Guidance' },
  { reference: 'PSA.32.8', category: 'Divine Guidance' },
  { reference: 'PSA.37.5', category: 'Divine Guidance' },
  { reference: 'PSA.43.3', category: 'Divine Guidance' },
  { reference: 'PSA.48.14', category: 'Divine Guidance' },
  { reference: 'PSA.61.2', category: 'Divine Guidance' },
  { reference: 'PSA.73.24', category: 'Divine Guidance' },
  { reference: 'PSA.78.14', category: 'Divine Guidance' },
  { reference: 'PSA.89.15', category: 'Divine Guidance' },
  { reference: 'PSA.103.13', category: 'Divine Guidance' },
  { reference: 'PSA.119.105', category: 'Divine Guidance' },
  { reference: 'PSA.139.10', category: 'Divine Guidance' },
  { reference: 'PSA.143.8', category: 'Divine Guidance' },
  { reference: 'PRO.3.5', category: 'Divine Guidance' },
  { reference: 'PRO.3.6', category: 'Divine Guidance' },
  { reference: 'PRO.4.11', category: 'Divine Guidance' },
  { reference: 'PRO.11.3', category: 'Divine Guidance' },
  { reference: 'PRO.16.9', category: 'Divine Guidance' },
  { reference: 'ISA.30.21', category: 'Divine Guidance' },
  { reference: 'ISA.42.16', category: 'Divine Guidance' },
  { reference: 'ISA.48.17', category: 'Divine Guidance' },
  { reference: 'ISA.58.11', category: 'Divine Guidance' },
  { reference: 'JER.3.15', category: 'Divine Guidance' },
  { reference: 'JER.10.23', category: 'Divine Guidance' },
  { reference: 'JER.29.11', category: 'Divine Guidance' },
  { reference: 'JHN.14.26', category: 'Divine Guidance' },
  { reference: 'JHN.16.13', category: 'Divine Guidance' },
  { reference: 'ROM.8.14', category: 'Divine Guidance' },
  { reference: 'GAL.5.16', category: 'Divine Guidance' },
  { reference: 'GAL.5.18', category: 'Divine Guidance' },
  { reference: 'JAM.1.5', category: 'Divine Guidance' },
  { reference: '1JN.2.27', category: 'Divine Guidance' },
  { reference: 'REV.7.17', category: 'Divine Guidance' }
];
