import type { VerseInfo } from '../../types';

export const HOPE: VerseInfo[] = [
  // Previous verses remain...
  // Adding 45 new verses
  { reference: 'JOB.11.18', category: 'Hope & Encouragement' },
  { reference: 'PSA.9.18', category: 'Hope & Encouragement' },
  { reference: 'PSA.25.3', category: 'Hope & Encouragement' },
  { reference: 'PSA.25.5', category: 'Hope & Encouragement' },
  { reference: 'PSA.31.24', category: 'Hope & Encouragement' },
  { reference: 'PSA.33.18', category: 'Hope & Encouragement' },
  { reference: 'PSA.33.22', category: 'Hope & Encouragement' },
  { reference: 'PSA.38.15', category: 'Hope & Encouragement' },
  { reference: 'PSA.39.7', category: 'Hope & Encouragement' },
  { reference: 'PSA.42.5', category: 'Hope & Encouragement' },
  { reference: 'PSA.62.5', category: 'Hope & Encouragement' },
  { reference: 'PSA.65.5', category: 'Hope & Encouragement' },
  { reference: 'PSA.71.5', category: 'Hope & Encouragement' },
  { reference: 'PSA.78.7', category: 'Hope & Encouragement' },
  { reference: 'PSA.119.74', category: 'Hope & Encouragement' },
  { reference: 'PSA.119.81', category: 'Hope & Encouragement' },
  { reference: 'PSA.130.7', category: 'Hope & Encouragement' },
  { reference: 'PSA.146.5', category: 'Hope & Encouragement' },
  { reference: 'PSA.147.11', category: 'Hope & Encouragement' },
  { reference: 'PRO.10.28', category: 'Hope & Encouragement' },
  { reference: 'PRO.13.12', category: 'Hope & Encouragement' },
  { reference: 'PRO.23.18', category: 'Hope & Encouragement' },
  { reference: 'ISA.40.31', category: 'Hope & Encouragement' },
  { reference: 'ISA.41.10', category: 'Hope & Encouragement' },
  { reference: 'ISA.43.2', category: 'Hope & Encouragement' },
  { reference: 'JER.17.7', category: 'Hope & Encouragement' },
  { reference: 'JER.29.11', category: 'Hope & Encouragement' },
  { reference: 'LAM.3.21', category: 'Hope & Encouragement' },
  { reference: 'LAM.3.24', category: 'Hope & Encouragement' },
  { reference: 'LAM.3.26', category: 'Hope & Encouragement' },
  { reference: 'JOL.3.16', category: 'Hope & Encouragement' },
  { reference: 'MIC.7.7', category: 'Hope & Encouragement' },
  { reference: 'HAB.3.17', category: 'Hope & Encouragement' },
  { reference: 'ZEC.9.12', category: 'Hope & Encouragement' },
  { reference: 'ACT.23.6', category: 'Hope & Encouragement' },
  { reference: 'ACT.24.15', category: 'Hope & Encouragement' },
  { reference: 'ROM.5.2', category: 'Hope & Encouragement' },
  { reference: 'ROM.5.4', category: 'Hope & Encouragement' },
  { reference: 'ROM.8.24', category: 'Hope & Encouragement' },
  { reference: 'ROM.12.12', category: 'Hope & Encouragement' },
  { reference: 'ROM.15.4', category: 'Hope & Encouragement' },
  { reference: 'ROM.15.13', category: 'Hope & Encouragement' },
  { reference: '2CO.3.12', category: 'Hope & Encouragement' },
  { reference: 'COL.1.27', category: 'Hope & Encouragement' },
  { reference: '1TH.5.8', category: 'Hope & Encouragement' }
];
