import type { VerseInfo } from '../../types';

export const PRAYER_FASTING: VerseInfo[] = [
  // Previous verses remain...
  // Adding 40 new verses
  { reference: 'PSA.5.3', category: 'Prayer & Fasting' },
  { reference: 'PSA.17.1', category: 'Prayer & Fasting' },
  { reference: 'PSA.34.15', category: 'Prayer & Fasting' },
  { reference: 'PSA.55.17', category: 'Prayer & Fasting' },
  { reference: 'PSA.66.17', category: 'Prayer & Fasting' },
  { reference: 'PSA.86.3', category: 'Prayer & Fasting' },
  { reference: 'PSA.141.2', category: 'Prayer & Fasting' },
  { reference: 'PRO.15.8', category: 'Prayer & Fasting' },
  { reference: 'ISA.56.7', category: 'Prayer & Fasting' },
  { reference: 'JER.29.12', category: 'Prayer & Fasting' },
  { reference: 'MAT.5.44', category: 'Prayer & Fasting' },
  { reference: 'MAT.6.7', category: 'Prayer & Fasting' },
  { reference: 'MAT.6.9', category: 'Prayer & Fasting' },
  { reference: 'MAT.7.7', category: 'Prayer & Fasting' },
  { reference: 'MAT.18.19', category: 'Prayer & Fasting' },
  { reference: 'MAT.21.22', category: 'Prayer & Fasting' },
  { reference: 'MAT.26.41', category: 'Prayer & Fasting' },
  { reference: 'MRK.1.35', category: 'Prayer & Fasting' },
  { reference: 'MRK.9.29', category: 'Prayer & Fasting' },
  { reference: 'MRK.11.24', category: 'Prayer & Fasting' },
  { reference: 'LUK.6.12', category: 'Prayer & Fasting' },
  { reference: 'LUK.11.1', category: 'Prayer & Fasting' },
  { reference: 'LUK.18.1', category: 'Prayer & Fasting' },
  { reference: 'LUK.21.36', category: 'Prayer & Fasting' },
  { reference: 'JHN.15.7', category: 'Prayer & Fasting' },
  { reference: 'JHN.16.24', category: 'Prayer & Fasting' },
  { reference: 'ACT.1.14', category: 'Prayer & Fasting' },
  { reference: 'ACT.2.42', category: 'Prayer & Fasting' },
  { reference: 'ACT.6.4', category: 'Prayer & Fasting' },
  { reference: 'ACT.10.9', category: 'Prayer & Fasting' },
  { reference: 'ROM.8.26', category: 'Prayer & Fasting' },
  { reference: 'ROM.12.12', category: 'Prayer & Fasting' },
  { reference: 'EPH.6.18', category: 'Prayer & Fasting' },
  { reference: 'PHP.4.6', category: 'Prayer & Fasting' },
  { reference: 'COL.4.2', category: 'Prayer & Fasting' },
  { reference: '1TH.5.17', category: 'Prayer & Fasting' },
  { reference: '1TI.2.1', category: 'Prayer & Fasting' },
  { reference: 'HEB.4.16', category: 'Prayer & Fasting' },
  { reference: 'JAM.5.13', category: 'Prayer & Fasting' },
  { reference: '1JN.5.14', category: 'Prayer & Fasting' }
];
