import type { VerseInfo } from '../../types';

export const PROMISES: VerseInfo[] = [
  // Previous verses remain...
  // Adding final 48 verses
  { reference: 'ROM.8.32', category: 'Promises of God' },
  { reference: 'ROM.8.37', category: 'Promises of God' },
  { reference: 'ROM.8.38', category: 'Promises of God' },
  { reference: 'ROM.8.39', category: 'Promises of God' },
  { reference: '1CO.2.9', category: 'Promises of God' },
  { reference: '1CO.10.13', category: 'Promises of God' },
  { reference: '2CO.1.20', category: 'Promises of God' },
  { reference: '2CO.4.17', category: 'Promises of God' },
  { reference: '2CO.6.16', category: 'Promises of God' },
  { reference: '2CO.6.17', category: 'Promises of God' },
  { reference: '2CO.6.18', category: 'Promises of God' },
  { reference: '2CO.7.1', category: 'Promises of God' },
  { reference: '2CO.9.8', category: 'Promises of God' },
  { reference: '2CO.12.9', category: 'Promises of God' },
  { reference: 'EPH.1.3', category: 'Promises of God' },
  { reference: 'EPH.2.10', category: 'Promises of God' },
  { reference: 'EPH.3.20', category: 'Promises of God' },
  { reference: 'PHP.1.6', category: 'Promises of God' },
  { reference: 'PHP.4.7', category: 'Promises of God' },
  { reference: 'PHP.4.13', category: 'Promises of God' },
  { reference: 'PHP.4.19', category: 'Promises of God' },
  { reference: 'COL.1.27', category: 'Promises of God' },
  { reference: '1TH.5.24', category: 'Promises of God' },
  { reference: '2TH.3.3', category: 'Promises of God' },
  { reference: '2TI.1.7', category: 'Promises of God' },
  { reference: '2TI.2.11', category: 'Promises of God' },
  { reference: '2TI.2.12', category: 'Promises of God' },
  { reference: '2TI.2.13', category: 'Promises of God' },
  { reference: 'HEB.4.16', category: 'Promises of God' },
  { reference: 'HEB.6.10', category: 'Promises of God' },
  { reference: 'HEB.8.10', category: 'Promises of God' },
  { reference: 'HEB.8.12', category: 'Promises of God' },
  { reference: 'HEB.10.23', category: 'Promises of God' },
  { reference: 'HEB.10.36', category: 'Promises of God' },
  { reference: 'HEB.13.5', category: 'Promises of God' },
  { reference: 'HEB.13.6', category: 'Promises of God' },
  { reference: 'JAM.1.12', category: 'Promises of God' },
  { reference: 'JAM.4.7', category: 'Promises of God' },
  { reference: 'JAM.4.8', category: 'Promises of God' },
  { reference: '1PE.2.9', category: 'Promises of God' },
  { reference: '1PE.5.6', category: 'Promises of God' },
  { reference: '1PE.5.7', category: 'Promises of God' },
  { reference: '1PE.5.10', category: 'Promises of God' },
  { reference: '2PE.1.3', category: 'Promises of God' },
  { reference: '2PE.1.4', category: 'Promises of God' },
  { reference: '1JN.1.7', category: 'Promises of God' },
  { reference: '1JN.1.9', category: 'Promises of God' },
  { reference: 'REV.21.4', category: 'Promises of God' }
];
