import type { VerseInfo } from '../../types';

export const REPENTANCE: VerseInfo[] = [
  // Previous verses remain...
  // Adding 45 new verses
  { reference: 'LEV.26.40', category: 'Repentance & Forgiveness' },
  { reference: 'DEU.4.29', category: 'Repentance & Forgiveness' },
  { reference: 'DEU.30.2', category: 'Repentance & Forgiveness' },
  { reference: '1KI.8.47', category: 'Repentance & Forgiveness' },
  { reference: '2CH.7.14', category: 'Repentance & Forgiveness' },
  { reference: 'JOB.11.13', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.32.1', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.32.2', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.34.14', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.34.18', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.38.18', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.51.1', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.51.2', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.51.3', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.51.17', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.86.5', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.103.12', category: 'Repentance & Forgiveness' },
  { reference: 'PSA.130.4', category: 'Repentance & Forgiveness' },
  { reference: 'PRO.28.13', category: 'Repentance & Forgiveness' },
  { reference: 'ISA.1.16', category: 'Repentance & Forgiveness' },
  { reference: 'ISA.1.17', category: 'Repentance & Forgiveness' },
  { reference: 'ISA.30.15', category: 'Repentance & Forgiveness' },
  { reference: 'ISA.43.25', category: 'Repentance & Forgiveness' },
  { reference: 'ISA.44.22', category: 'Repentance & Forgiveness' },
  { reference: 'ISA.55.7', category: 'Repentance & Forgiveness' },
  { reference: 'JER.3.12', category: 'Repentance & Forgiveness' },
  { reference: 'JER.3.13', category: 'Repentance & Forgiveness' },
  { reference: 'JER.3.22', category: 'Repentance & Forgiveness' },
  { reference: 'JER.18.8', category: 'Repentance & Forgiveness' },
  { reference: 'EZK.18.21', category: 'Repentance & Forgiveness' },
  { reference: 'EZK.18.27', category: 'Repentance & Forgiveness' },
  { reference: 'EZK.18.30', category: 'Repentance & Forgiveness' },
  { reference: 'EZK.33.11', category: 'Repentance & Forgiveness' },
  { reference: 'HOS.6.1', category: 'Repentance & Forgiveness' },
  { reference: 'HOS.14.1', category: 'Repentance & Forgiveness' },
  { reference: 'JOL.2.12', category: 'Repentance & Forgiveness' },
  { reference: 'JOL.2.13', category: 'Repentance & Forgiveness' },
  { reference: 'AMO.5.6', category: 'Repentance & Forgiveness' },
  { reference: 'JON.3.8', category: 'Repentance & Forgiveness' },
  { reference: 'ZEC.1.3', category: 'Repentance & Forgiveness' },
  { reference: 'MAL.3.7', category: 'Repentance & Forgiveness' },
  { reference: 'MAT.3.2', category: 'Repentance & Forgiveness' },
  { reference: 'MAT.4.17', category: 'Repentance & Forgiveness' },
  { reference: 'LUK.13.3', category: 'Repentance & Forgiveness' },
  { reference: 'ACT.3.19', category: 'Repentance & Forgiveness' }
];
