import type { VerseInfo } from '../../types';

export const SPIRITUAL_WARFARE: VerseInfo[] = [
  // Existing verses...
  { reference: 'EPH.6.11', category: 'Spiritual Warfare' },
  { reference: '1PE.5.8', category: 'Spiritual Warfare' },
  { reference: 'JAS.4.7', category: 'Spiritual Warfare' },
  { reference: '2CO.10.4', category: 'Spiritual Warfare' },
  { reference: 'EPH.6.12', category: 'Spiritual Warfare' },
  { reference: '1JN.4.4', category: 'Spiritual Warfare' },
  { reference: 'REV.12.11', category: 'Spiritual Warfare' },
  { reference: 'EPH.6.13', category: 'Spiritual Warfare' },
  { reference: '2TI.1.7', category: 'Spiritual Warfare' },
  { reference: 'ROM.8.37', category: 'Spiritual Warfare' },
  { reference: '1CO.10.13', category: 'Spiritual Warfare' },
  { reference: 'COL.2.15', category: 'Spiritual Warfare' },
  { reference: '2CO.2.11', category: 'Spiritual Warfare' },
  { reference: 'EPH.6.16', category: 'Spiritual Warfare' },
  { reference: '1JN.5.4', category: 'Spiritual Warfare' },
  { reference: 'ROM.16.20', category: 'Spiritual Warfare' },
  { reference: 'JAS.4.8', category: 'Spiritual Warfare' },
  { reference: 'EPH.6.17', category: 'Spiritual Warfare' },
  { reference: '2CO.10.5', category: 'Spiritual Warfare' },
  // Adding new verses
  { reference: 'EPH.6.14', category: 'Spiritual Warfare' },
  { reference: 'EPH.6.15', category: 'Spiritual Warfare' },
  { reference: 'EPH.6.18', category: 'Spiritual Warfare' },
  { reference: '1TH.5.8', category: 'Spiritual Warfare' },
  { reference: '1PE.5.9', category: 'Spiritual Warfare' },
  { reference: 'REV.12.10', category: 'Spiritual Warfare' },
  { reference: '2CO.10.3', category: 'Spiritual Warfare' },
  { reference: 'JUD.1.9', category: 'Spiritual Warfare' },
  { reference: '1JN.3.8', category: 'Spiritual Warfare' },
  { reference: 'COL.1.13', category: 'Spiritual Warfare' },
  { reference: 'MAT.16.19', category: 'Spiritual Warfare' },
  { reference: 'LUK.10.19', category: 'Spiritual Warfare' },
  { reference: 'ISA.54.17', category: 'Spiritual Warfare' },
  { reference: 'MAT.12.29', category: 'Spiritual Warfare' },
  { reference: '2CO.6.7', category: 'Spiritual Warfare' },
  { reference: 'REV.19.11', category: 'Spiritual Warfare' },
  { reference: '1JN.4.1', category: 'Spiritual Warfare' },
  { reference: 'PHP.2.10', category: 'Spiritual Warfare' },
  { reference: 'COL.2.10', category: 'Spiritual Warfare' },
  { reference: 'HEB.2.14', category: 'Spiritual Warfare' },
  { reference: 'ZEC.4.6', category: 'Spiritual Warfare' }
];
