import type { VerseInfo } from '../../types';

export const STRENGTH: VerseInfo[] = [
  // Previous verses remain...
  // Adding 40 new verses
  { reference: 'GEN.28.15', category: 'Strength & Courage' },
  { reference: 'EXO.15.2', category: 'Strength & Courage' },
  { reference: 'DEU.20.4', category: 'Strength & Courage' },
  { reference: 'DEU.31.6', category: 'Strength & Courage' },
  { reference: 'JOS.1.6', category: 'Strength & Courage' },
  { reference: 'JOS.1.7', category: 'Strength & Courage' },
  { reference: 'JOS.1.9', category: 'Strength & Courage' },
  { reference: 'JOS.10.25', category: 'Strength & Courage' },
  { reference: '1SA.30.6', category: 'Strength & Courage' },
  { reference: '1CH.16.11', category: 'Strength & Courage' },
  { reference: '2CH.15.7', category: 'Strength & Courage' },
  { reference: 'NEH.8.10', category: 'Strength & Courage' },
  { reference: 'PSA.18.1', category: 'Strength & Courage' },
  { reference: 'PSA.18.32', category: 'Strength & Courage' },
  { reference: 'PSA.27.14', category: 'Strength & Courage' },
  { reference: 'PSA.28.7', category: 'Strength & Courage' },
  { reference: 'PSA.29.11', category: 'Strength & Courage' },
  { reference: 'PSA.31.24', category: 'Strength & Courage' },
  { reference: 'PSA.46.1', category: 'Strength & Courage' },
  { reference: 'PSA.73.26', category: 'Strength & Courage' },
  { reference: 'PSA.81.1', category: 'Strength & Courage' },
  { reference: 'PSA.105.4', category: 'Strength & Courage' },
  { reference: 'PSA.118.14', category: 'Strength & Courage' },
  { reference: 'PSA.119.28', category: 'Strength & Courage' },
  { reference: 'PSA.138.3', category: 'Strength & Courage' },
  { reference: 'ISA.12.2', category: 'Strength & Courage' },
  { reference: 'ISA.25.4', category: 'Strength & Courage' },
  { reference: 'ISA.33.2', category: 'Strength & Courage' },
  { reference: 'ISA.35.4', category: 'Strength & Courage' },
  { reference: 'ISA.40.29', category: 'Strength & Courage' },
  { reference: 'ISA.40.31', category: 'Strength & Courage' },
  { reference: 'ISA.41.10', category: 'Strength & Courage' },
  { reference: 'HAB.3.19', category: 'Strength & Courage' },
  { reference: 'ZEP.3.17', category: 'Strength & Courage' },
  { reference: 'ZEC.4.6', category: 'Strength & Courage' },
  { reference: '1CO.16.13', category: 'Strength & Courage' },
  { reference: '2CO.12.9', category: 'Strength & Courage' },
  { reference: 'EPH.3.16', category: 'Strength & Courage' },
  { reference: 'EPH.6.10', category: 'Strength & Courage' },
  { reference: 'PHP.4.13', category: 'Strength & Courage' }
];
