import type { VerseInfo } from '../../types';

export const WISDOM: VerseInfo[] = [
  // Existing verses...
  { reference: 'PRO.1.7', category: 'Wisdom & Knowledge' },
  { reference: 'JAS.1.5', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.2.6', category: 'Wisdom & Knowledge' },
  { reference: 'COL.2.3', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.3.13', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.4.7', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.9.10', category: 'Wisdom & Knowledge' },
  { reference: 'JAS.3.17', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.15.33', category: 'Wisdom & Knowledge' },
  { reference: 'PSA.111.10', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.18.15', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.19.20', category: 'Wisdom & Knowledge' },
  { reference: 'ECC.7.12', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.24.14', category: 'Wisdom & Knowledge' },
  { reference: 'COL.3.16', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.8.11', category: 'Wisdom & Knowledge' },
  { reference: 'ECC.2.26', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.16.16', category: 'Wisdom & Knowledge' },
  { reference: 'DAN.2.21', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.2.10', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.13.20', category: 'Wisdom & Knowledge' },
  { reference: 'ECC.7.19', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.14.8', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.23.23', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.29.3', category: 'Wisdom & Knowledge' },
  // Adding new verses
  { reference: 'PRO.1.5', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.2.1', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.3.7', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.4.5', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.8.1', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.10.14', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.11.2', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.12.1', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.13.1', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.14.1', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.15.1', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.16.16', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.17.24', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.18.15', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.19.8', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.20.15', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.21.11', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.22.17', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.23.12', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.24.3', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.25.2', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.26.12', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.28.26', category: 'Wisdom & Knowledge' },
  { reference: 'PRO.30.3', category: 'Wisdom & Knowledge' },
  { reference: 'ECC.1.18', category: 'Wisdom & Knowledge' }
];
