import type { VerseInfo } from '../../types';

export const WORSHIP_PRAISE: VerseInfo[] = [
  // Previous verses remain...
  // Adding 40 new verses
  { reference: 'PSA.5.11', category: 'Worship & Praise' },
  { reference: 'PSA.7.17', category: 'Worship & Praise' },
  { reference: 'PSA.13.6', category: 'Worship & Praise' },
  { reference: 'PSA.16.7', category: 'Worship & Praise' },
  { reference: 'PSA.18.49', category: 'Worship & Praise' },
  { reference: 'PSA.22.22', category: 'Worship & Praise' },
  { reference: 'PSA.26.12', category: 'Worship & Praise' },
  { reference: 'PSA.28.7', category: 'Worship & Praise' },
  { reference: 'PSA.30.12', category: 'Worship & Praise' },
  { reference: 'PSA.34.3', category: 'Worship & Praise' },
  { reference: 'PSA.35.28', category: 'Worship & Praise' },
  { reference: 'PSA.42.11', category: 'Worship & Praise' },
  { reference: 'PSA.43.4', category: 'Worship & Praise' },
  { reference: 'PSA.47.7', category: 'Worship & Praise' },
  { reference: 'PSA.51.15', category: 'Worship & Praise' },
  { reference: 'PSA.56.12', category: 'Worship & Praise' },
  { reference: 'PSA.57.7', category: 'Worship & Praise' },
  { reference: 'PSA.63.3', category: 'Worship & Praise' },
  { reference: 'PSA.66.2', category: 'Worship & Praise' },
  { reference: 'PSA.67.3', category: 'Worship & Praise' },
  { reference: 'PSA.68.32', category: 'Worship & Praise' },
  { reference: 'PSA.69.34', category: 'Worship & Praise' },
  { reference: 'PSA.71.14', category: 'Worship & Praise' },
  { reference: 'PSA.75.9', category: 'Worship & Praise' },
  { reference: 'PSA.79.13', category: 'Worship & Praise' },
  { reference: 'PSA.86.12', category: 'Worship & Praise' },
  { reference: 'PSA.89.15', category: 'Worship & Praise' },
  { reference: 'PSA.92.4', category: 'Worship & Praise' },
  { reference: 'PSA.95.6', category: 'Worship & Praise' },
  { reference: 'PSA.98.4', category: 'Worship & Praise' },
  { reference: 'PSA.100.2', category: 'Worship & Praise' },
  { reference: 'PSA.101.1', category: 'Worship & Praise' },
  { reference: 'PSA.103.1', category: 'Worship & Praise' },
  { reference: 'PSA.104.33', category: 'Worship & Praise' },
  { reference: 'PSA.105.2', category: 'Worship & Praise' },
  { reference: 'PSA.106.1', category: 'Worship & Praise' },
  { reference: 'PSA.107.1', category: 'Worship & Praise' },
  { reference: 'PSA.108.1', category: 'Worship & Praise' },
  { reference: 'PSA.109.30', category: 'Worship & Praise' },
  { reference: 'PSA.111.1', category: 'Worship & Praise' }
];
