export const BOOK_NAMES: Record<string, string> = {
  'GEN': 'Genesis',
  'EXO': 'Exodus',
  'LEV': 'Leviticus',
  'NUM': 'Numbers',
  'DEU': 'Deuteronomy',
  'JOS': 'Joshua',
  'JDG': 'Judges',
  'RUT': 'Ruth',
  '1SA': '1 Samuel',
  '2SA': '2 Samuel',
  '1KI': '1 Kings',
  '2KI': '2 Kings',
  '1CH': '1 Chronicles',
  '2CH': '2 Chronicles',
  'EZR': 'Ezra',
  'NEH': 'Nehemiah',
  'EST': 'Esther',
  'JOB': 'Job',
  'PSA': 'Psalm',
  'PRO': 'Proverbs',
  'ECC': 'Ecclesiastes',
  'SNG': 'Song of Solomon',
  'ISA': 'Isaiah',
  'JER': 'Jeremiah',
  'LAM': 'Lamentations',
  'EZK': 'Ezekiel',
  'DAN': 'Daniel',
  'HOS': 'Hosea',
  'JOL': 'Joel',
  'AMO': 'Amos',
  'OBA': 'Obadiah',
  'JON': 'Jonah',
  'MIC': 'Micah',
  'NAM': 'Nahum',
  'HAB': 'Habakkuk',
  'ZEP': 'Zephaniah',
  'HAG': 'Haggai',
  'ZEC': 'Zechariah',
  'MAL': 'Malachi',
  'MAT': 'Matthew',
  'MRK': 'Mark',
  'LUK': 'Luke',
  'JHN': 'John',
  'ACT': 'Acts',
  'ROM': 'Romans',
  '1CO': '1 Corinthians',
  '2CO': '2 Corinthians',
  'GAL': 'Galatians',
  'EPH': 'Ephesians',
  'PHP': 'Philippians',
  'COL': 'Colossians',
  '1TH': '1 Thessalonians',
  '2TH': '2 Thessalonians',
  '1TI': '1 Timothy',
  '2TI': '2 Timothy',
  'TIT': 'Titus',
  'PHM': 'Philemon',
  'HEB': 'Hebrews',
  'JAS': 'James',
  '1PE': '1 Peter',
  '2PE': '2 Peter',
  '1JN': '1 John',
  '2JN': '2 John',
  '3JN': '3 John',
  'JUD': 'Jude',
  'REV': 'Revelation'
};

// Reverse mapping for API compatibility
export const API_BOOK_CODES: Record<string, string> = {
  'GEN': 'GEN',
  'EXO': 'EXO',
  'LEV': 'LEV',
  'NUM': 'NUM',
  'DEU': 'DEU',
  'JOS': 'JOS',
  'JDG': 'JDG',
  'RUT': 'RUT',
  '1SA': '1SA',
  '2SA': '2SA',
  '1KI': '1KI',
  '2KI': '2KI',
  '1CH': '1CH',
  '2CH': '2CH',
  'EZR': 'EZR',
  'NEH': 'NEH',
  'EST': 'EST',
  'JOB': 'JOB',
  'PSA': 'PSA',
  'PRO': 'PRO',
  'ECC': 'ECC',
  'SNG': 'SNG',
  'ISA': 'ISA',
  'JER': 'JER',
  'LAM': 'LAM',
  'EZK': 'EZK',
  'DAN': 'DAN',
  'HOS': 'HOS',
  'JOL': 'JOL',
  'AMO': 'AMO',
  'OBA': 'OBA',
  'JON': 'JON',
  'MIC': 'MIC',
  'NAH': 'NAH',
  'HAB': 'HAB',
  'ZEP': 'ZEP',
  'HAG': 'HAG',
  'ZEC': 'ZEC',
  'MAL': 'MAL',
  'MAT': 'MAT',
  'MRK': 'MRK',
  'LUK': 'LUK',
  'JHN': 'JHN',
  'ACT': 'ACT',
  'ROM': 'ROM',
  '1CO': '1CO',
  '2CO': '2CO',
  'GAL': 'GAL',
  'EPH': 'EPH',
  'PHP': 'PHP',
  'COL': 'COL',
  '1TH': '1TH',
  '2TH': '2TH',
  '1TI': '1TI',
  '2TI': '2TI',
  'TIT': 'TIT',
  'PHM': 'PHM',
  'HEB': 'HEB',
  'JAS': 'JAS',
  '1PE': '1PE',
  '2PE': '2PE',
  '1JN': '1JN',
  '2JN': '2JN',
  '3JN': '3JN',
  'JUD': 'JUD',
  'REV': 'REV'
};
